version: '3.4'

volumes:
    db-data:

services:
    database:
        image: postgres:13-alpine
        environment:
            - POSTGRES_DB=local
            - POSTGRES_USER=local
            - POSTGRES_PASSWORD=local
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data
